  # Inside your-values-repo/prod-env/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: my-app-values
    files:
      - values.yaml=production-values.yaml # Maps your file to a key